### ISSUE TITLE
Floating point exception in Lab 5/13 - Task1

### ISSUE THREAD

**Issue by saadiPro** [Mu-Ahmad/OOP-CMP-244-241#2]
An error occurs during the fourth operation (average), the program returns **Floating point exception** and terminates.
 @alirazamumtaz  can you address it.

**Runtime Screen**
**2 4 3                                                                                                                         
2                                                                                                                             
7 3                                                                                                                           
40 O 50 O 60 N                                                                                                                
4 2                                                                                                                           
Floating point exception (core dumped)** 
### Screen Exit.

**Comment by locus-x64** [comment]
OH! Thank you @saadiPro I got that point.
